### PR TITLE
Response

### PR DESCRIPTION
**Pull request by MishaHerscu**
is this a good way to show the result data to the browser?

### CODE REVIEW

**Comment by jrhorn424** [comment]
Looks good to me. Were you looking for any specific feedback?

One thing you might be interested to know is that later in the course, we'll use `.then()` instead of `.done()`. They both work in jQuery, but they behave differently. Check this out: http://stackoverflow.com/questions/26530282/chaining-multiple-done-callbacks-to-the-same-deferred-promise

**Comment by jrhorn424** [comment]
The highlighted messages aren't good commit summaries. I only checked a handful of commits, but you didn't seem to have longer explanations in them, either.

response_by_mishaherscu_ _pull_request__6_ _ga-wdi-boston_jquery-ajax-patch

**Comment by jrhorn424** [comment]
I really, really like what you're doing to hide and display different parts of the app. That's the basics of "front-end routing" and definitely a good problem to solve.

**Comment by MishaHerscu** [comment]
Thanks - yeah, i was just looking for general feedback.

you are right about my commits..i was being lazy. i'll start putting in
actual messages

**Pull request closed without merging**
